### ISSUE TITLE
Collision checking with time

### ISSUE THREAD

**Issue by sdeglurkar** [HJReachability/fastrack#4]
FaSTrack's environment.h does not have functionality to do time-varying collision checking - its IsValid method does not have an argument for a time stamp corresponding to the position:
bool IsValid(const Vector3d &position, const Box &bound) const;

**Comment by dfridovi** [comment]
Done. Please see https://github.com/HJReachability/fastrack/blob/master/ros/src/fastrack/include/fastrack/environment/environment.h and https://github.com/HJReachability/fastrack/blob/master/ros/src/fastrack/include/fastrack/environment/balls_in_box.h
