### ISSUE TITLE
when I  roslaunch fastrack replanner.launch, there is always this info, I don't know if it is correct

### ISSUE THREAD

**Issue by kevinstudyprogram** [HJReachability/fastrack#9]
[ INFO] [1565505794.668327332]: waitForService: Service [/replan] has not been advertised, waiting...

**Comment by dfridovi** [comment]
That’s because you’re launching a single node of the *many* required to run a demo. Check out the fastrack_crazyflie_demos package for further details.

**Comment by kevinstudyprogram** [comment]
> That’s because you’re launching a single node of the _many_ required to run a demo. Check out the fastrack_crazyflie_demos package for further details.
